# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app_version:
        ios:
            latest: '1.23.0'
            minRequired: '1.23.0'
            forceUpdate: true
            storeUrl: 'https://apps.apple.com/app/id6758859179'

        android:
            latest: '1.23.0'
            minRequired: '1.23.0'
            forceUpdate: true
            storeUrl: 'market://details?id=com.cookienumerique.selen'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    App\Infrastructure\Auth\GoogleTokenVerifier:
        arguments:
            $clientId: "%env(GOOGLE_CLIENT_ID)%"
    App\Security\JwtTokenManager:
        arguments:
            $inner: "@lexik_jwt_authentication.jwt_manager"
    App\EventListener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
        arguments:
            $debug: '%kernel.debug%'
    App\Controller\MediaController:
        arguments:
            $storageDir: '%env(MOUNT_PATH_CONTAINER)%'
    App\Application\Subscription\Google\GoogleSubscriptionVerifier:
        arguments:
            $googleAuthConfigPath: '%kernel.project_dir%/%env(GOOGLE_SERVICE_ACCOUNT_JSON)%'
            $packageName: '%env(ANDROID_PACKAGE_NAME)%'
    App\Application\Subscription\Apple\AppleSubscriptionValidator:
        arguments:
            $appleBundleId: '%env(APPLE_BUNDLE_ID)%'
            $environment: '%env(APP_ENV)%'
    App\Application\Ai\OpenAiClient:
        arguments:
            $apiKey: '%env(OPENAI_API_KEY)%'